### ISSUE TITLE
Installation error on Android (termux)

### ISSUE THREAD

**Issue by SamXuLing** [nikolaxhristov/pipeline#3]
Hello again!
The issue is exacly like on [astro-compress #57](https://github.com/astro-community/astro-compress/issues/57) last month, which _Sharp_ isn't supported on Android.

**Comment by nikolaxhristov** [comment]
are you installing the no-sharp branch? `npm install -D -E nikolaxhristov/pipeline#no-sharp`

**Comment by SamXuLing** [comment]
I'm often to follow what's on the _readme_ file and forgot to check the branch. well my bad 😅

**Comment by nikolaxhristov** [comment]
I'll update the `no-sharp` branch to the latest version shortly. It might still not work with the newest options, apply, pipe etc.
